name: Windows 11 Remote Environment

on:
  workflow_dispatch:  # Allows manual triggering

jobs:
  setup-windows11:
    runs-on: windows-2022  # This is Windows 11 equivalent in GitHub Actions
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup tmate session for remote access
        uses: mxschmitt/action-tmate@v3
        with:
          limit-access-to-actor: true
